# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='album_logo'),
        ),
    ]
